# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 11:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subreddapp', '0003_auto_20161121_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_comment',
            name='parent_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='subreddapp.Post_Main'),
        ),
        migrations.AlterField(
            model_name='post_comment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post_main',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mainposts', to=settings.AUTH_USER_MODEL),
        ),
    ]
