# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subreddapp', '0004_auto_20161122_1403'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_Comment',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Post_Main',
            new_name='Post',
        ),
    ]
