# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subreddapp', '0005_auto_20161123_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-published_date',)},
        ),
    ]
