# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subreddapp', '0009_auto_20161125_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_comments', to='subreddapp.Comment'),
        ),
    ]
