# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subreddapp', '0014_auto_20161129_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='username',
            new_name='user',
        ),
    ]
